name: Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: xdebug
      - name: Install Dependencies
        run: composer update --no-interaction --no-suggest
      - name: Run PHPUnit
        run: vendor/bin/phpunit